theme: jekyll-theme-cayman
page:
  title: Multistakeholder Recommender Systems in Tourism
  description: Multistakeholder Recommender Systems in Tourism - Balakrishnan and Wörndl
github:
  is_project_page: false